#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

. /etc/functions.sh
[ $# = 0 ] && { echo "  $0 <group>"; exit; }
[ "x$1" = "x-a" ] && {
	config_cb() {
		[ ofswitch != "$1" -o -z "$2" ] || eval "$0 $2"
	}
	config_load openflow
	exit
}

include /lib/openflow
scan_ofinterfaces

# kill ofprotocol and ofdatapath
pids="$(head -n 1 -q /var/run/ofprotocol.pid /var/run/ofdatapath.pid 2>/dev/null)"
for pid in $pids; do
	[ -d "/proc/$pid" ] && {
		kill $pid
		[ -d "/proc/$pid" ] && {
			sleep 1
			kill -9 $pid 2>/dev/null >/dev/null
		}
	}
done
rm -f /var/run/ofprotocol.pid /var/run/ofdatapath.pid
			





